name: Deploy to Azure

on:
  push:
    branches:
      - main  # 或者是你的主分支名稱
  workflow_dispatch:  # 允許手動觸發

env:
  AZURE_WEBAPP_NAME: exam-platform    # 設置 Web App 名稱
  PYTHON_VERSION: '3.9'               # Python 版本

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests  # 如果有測試的話
      run: |
        python -m pytest
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        
    - name: Azure logout
      run: |
        az logout
